postgres:
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  dbname: tfmv
  sslmode: disable
  tables:
    - flights
    - your_second_table  # Add more tables as needed
  concurrency: 4  # Number of concurrent table processing

pubsub:
  project_id: tfmv-371720
  topic_id: my_topic
  credentials: /Users/thomasmcgeehan/db2viz/db2viz/config/sa.json
