postgres:
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  dbname: Adventureworks
  sslmode: disable
  tables:
    - name: foo
      schema: production
      topic_id: foo_topic
  concurrency: 2

pubsub:
  project_id: tfmv-371720
  credentials: /Users/thomasmcgeehan/db2viz/db2viz/config/sa.json
  workers: 10
