postgres:
  host: localhost
  port: 5432
  user: postgres
  password: mysecretpassword
  dbname: tfmv
  sslmode: disable
  table: flights

pubsub:
  project_id: tfmv-371720
  topic_id: flights-topic
  credentials: /Users/thomasmcgeehan/db2viz/db2viz/config/sa.json  # Path to the service account JSON file
